# Target broker configuration, we'd recommend to have at least one fallback broker.
main_broker: "http://broker.eu-fr-par1.localhost"
fallback_brokers:
  - "http://broker.us-east-ny1.localhost"

zone: "dev"
region: "localhost"

# Max number of message that can be buffered, if full, send to broker
batch: 100
# Maximum interval to which we send a batch
batch_interval: 10

check_config_adapter:
  name: "static"
  checks:
    - type: "http"
      id: "id1"
      pretty_name: "60s endpoint check"
      endpoint: "https://my_endpoint/api/v1/healthy?system_only=true"
      interval: 60
      headers:
        Authorization: "Bearer..."

    - type: "tcp"
      id: "id2"
      pretty_name: "120s redis tcp check"
      endpoint: "my_tcp_endpoint:9123"
      secured: true
      interval: 120
