kafka:
  topic: "isok.agent.results"
  # Kafka producer configuration, see https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
  properties:
    group.id: "isok-broker"
    bootstrap.servers: "localhost:9092"

api:
  listen_address: "127.0.0.1:8000"
