name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      - uses: taiki-e/install-action@v2.47.0
        with:
          tool: cargo-nextest@0.9.87
      - uses: actions/checkout@v4
      - run: cargo nextest run --all-features

  build-examples:
    name: cargo build examples
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      - uses: taiki-e/install-action@v2.47.0
        with:
          tool: cargo-nextest@0.9.87
      - uses: actions/checkout@v4
      - run: cargo build
        working-directory: examples/isok-web-offloader